### ISSUE TITLE
browserify could not find module 'jQuery'

### ISSUE THREAD

**Issue by benzmuircroft** [bcherny/draggable#3]
browserify src/draggable.js --s Draggable | uglifyjs -c > draggable.js
Error: Cannot find module 'jQuery' from '/home/engine/node_modules/draggable/src'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)

**Comment by bcherny** [comment]
fixed via https://github.com/bcherny/draggable/commit/e34d6c7a8d426ced6ef1335df4860871330ec2c4

**Comment by adamburgess** [comment]
Not completely fixed - j**Q**uery is still required, which wasn't working for me (under jspm/systemjs on windows, might differ under other systems)
changing all requires to j**q**uery fixed it.

I couldn't figure out how to remove jquery as a dependency though, so ended up forking this and using es6's module importing and your small shim, which works for me.
